"""empty message

Revision ID: 1be9bcbf18c2
Revises: None
Create Date: 2014-08-06 18:52:11.013563

"""

# revision identifiers, used by Alembic.
revision = '1be9bcbf18c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
