"""empty message

Revision ID: 1c41f00ff38a
Revises: b86baa81263
Create Date: 2014-08-06 20:00:32.470711

"""

# revision identifiers, used by Alembic.
revision = '1c41f00ff38a'
down_revision = 'b86baa81263'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default='')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default='')
    op.drop_column('article', 'date_created')
    op.drop_column('article', 'category')
    op.drop_column('article', 'author')
    ### end Alembic commands ###
