"""empty message

Revision ID: b86baa81263
Revises: 1be9bcbf18c2
Create Date: 2014-08-06 19:41:11.844354

"""

# revision identifiers, used by Alembic.
revision = 'b86baa81263'
down_revision = '1be9bcbf18c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
